#!/usr/bin/env python3
"""Structural contract for the committed DRACU-RIOT packs (image + script).

The two packs are generated by tools/dracu_pack.py and tools/dracu_scn_pack.py and
committed under main/dracu_data/; the firmware indexes them by *pool-relative id*,
so a mismatch between the two packers would silently draw the wrong artwork or
skip a sprite.  This test re-parses both files with an independent reader and
cross-checks:

  * the image pack header/pool index (entries grouped by pool, ids contiguous);
  * every blocked payload (SD / BODY / FACE) against its declared entry geometry;
  * every sprite row's body/face entry indices and the CG patch bases;
  * every asset id the script pack references (bg / cg / sd / sprite) against the
    image pack's pool sizes -- this is the guard that keeps the two packers in
    sync.

Both packs are several megabytes, so the test skips cleanly when they are
absent (a checkout that only builds the app does not need them regenerated).

Run: python3 tests/test_dracu_pack_layout.py
"""

from __future__ import annotations

import struct
import sys
import unittest
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IMAGE_PACK = ROOT / "main" / "dracu_data" / "dracu_pack.bin"
SCRIPT_PACK = ROOT / "main" / "dracu_data" / "dracu_scn.bin"

HEADER = struct.Struct("<8sHHHHI")
SECTION = struct.Struct("<IIII")
ENTRY = struct.Struct("<IHBBHHHHHHHIIIH")
SPRITE = struct.Struct("<HHhh")
BLOCK_HEADER = struct.Struct("<6HI")
PAGE = struct.Struct("<IHHHBBBBBB")

POOL_BG, POOL_CG, POOL_SD, POOL_BODY, POOL_FACE = range(5)
POOL_NAMES = ("bg", "cg", "sd", "body", "face")
KIND_BG, KIND_CG, KIND_CG_DIFF, KIND_SD, KIND_BODY, KIND_FACE, KIND_MISSING = range(7)

SCN_HEADER = struct.Struct("<8sHHHHI")
SCN_BLOCK_HEADER = struct.Struct("<HHII")
SCN_BLOCK = struct.Struct("<III")


def read_sections(blob: bytes, expect_magic: bytes):
    assert len(blob) >= HEADER.size
    magic, version, header_size, section_count, _reserved, total = HEADER.unpack_from(blob)
    assert magic == expect_magic, magic
    assert total == len(blob), (total, len(blob))
    sections: dict[int, tuple[int, int, int]] = {}
    for index in range(section_count):
        kind, offset, count, size = SECTION.unpack_from(blob, HEADER.size + index * SECTION.size)
        assert offset + size <= len(blob)
        sections[kind] = (offset, count, size)
    assert header_size == HEADER.size + section_count * SECTION.size
    return version, sections


class ImagePackTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        if not IMAGE_PACK.is_file():
            raise unittest.SkipTest(f"缺少 {IMAGE_PACK}(先用 tools/dracu_pack.py 生成)")
        cls.blob = IMAGE_PACK.read_bytes()
        _version, cls.sections = read_sections(cls.blob, b"DRACUPK1")
        name_off, name_count, name_size = cls.sections[0]
        asset_off, asset_count, _asset_size = cls.sections[1]
        cls.name_off, cls.name_count, cls.name_size = name_off, name_count, name_size
        cls.asset_off, cls.asset_count = asset_off, asset_count
        cls.blob_off, _c, cls.blob_size = cls.sections[2]
        cls.sprite_off, cls.sprite_count, _s = cls.sections[3]
        cls.entries = []
        for index in range(asset_count):
            record = ENTRY.unpack_from(cls.blob, asset_off + index * ENTRY.size)
            (n_off, n_len, kind, pool, base, w, h, dx, dy, dw, dh, data_off, data_len,
             flags, _reserved) = record
            cls.entries.append(dict(index=index, name_off=n_off, name_len=n_len, kind=kind,
                                    pool=pool, base=base, w=w, h=h, dx=dx, dy=dy, dw=dw, dh=dh,
                                    data_off=data_off, data_len=data_len, flags=flags))
        cls.pools: dict[int, list[dict]] = {}
        for entry in cls.entries:
            cls.pools.setdefault(entry["pool"], []).append(entry)

    def name_of(self, entry: dict) -> str:
        off = self.name_off + entry["name_off"]
        return self.blob[off:off + entry["name_len"]].decode("utf-8")

    def payload(self, entry: dict) -> bytes:
        start = self.blob_off + entry["data_off"]
        return self.blob[start:start + entry["data_len"]]

    def test_pool_index_is_contiguous(self) -> None:
        """同一个池的条目必须在条目表里连排,固件才能用 id 直接算条目下标。"""
        seen: dict[int, int] = {}
        last = None
        for entry in self.entries:
            pool = entry["pool"]
            self.assertIn(pool, range(5))
            if pool != last:
                self.assertNotIn(pool, seen, f"{POOL_NAMES[pool]} 池不连续")
                seen[pool] = entry["index"]
            last = pool
        for pool in range(5):
            self.assertIn(pool, seen, f"{POOL_NAMES[pool]} 池为空")

    def test_title_art_lives_in_the_background_pool(self) -> None:
        """标题图和普通背景一起排在背景池里(id = 排序后的位置,不固定为 0)。

        固件启动时按名字查它,所以这里只要求它存在且是整屏 JPEG。
        """
        names = [self.name_of(entry) for entry in self.pools[POOL_BG]]
        self.assertIn("标题画面", names)
        title = self.pools[POOL_BG][names.index("标题画面")]
        self.assertEqual(title["kind"], KIND_BG)
        self.assertEqual((title["w"], title["h"]), (240, 320))
        self.assertEqual(len(names), len(set(names)), "背景名不能重复")

    def test_names_are_nul_terminated_and_within_pool(self) -> None:
        for entry in self.entries:
            off = self.name_off + entry["name_off"]
            self.assertLess(off + entry["name_len"], self.name_off + self.name_size)
            self.assertEqual(self.blob[off + entry["name_len"]], 0)
            self.assertNotEqual(entry["name_len"], 0)

    def test_cg_patch_bases_point_at_cgs(self) -> None:
        patches = [e for e in self.pools[POOL_CG] if e["kind"] == KIND_CG_DIFF]
        self.assertTrue(patches, "CG 补丁应当存在")
        for patch in patches:
            self.assertLess(patch["base"], self.asset_count)
            base = self.entries[patch["base"]]
            self.assertEqual(base["pool"], POOL_CG)
            self.assertEqual(base["kind"], KIND_CG)
            self.assertEqual((patch["w"], patch["h"]), (base["w"], base["h"]))
            self.assertGreater(patch["dw"], 0)
            self.assertGreater(patch["dh"], 0)
            # 载荷头:掩码长度 + 块数 + 块表
            payload = self.payload(patch)
            mask_len, block_count = struct.unpack_from("<II", payload, 0)
            self.assertGreater(block_count, 0)
            self.assertEqual(8 + 4 * block_count + mask_len, len(payload) - sum(
                struct.unpack_from("<I", payload, 8 + 4 * i)[0] for i in range(block_count)))

    def test_blocked_payloads_match_their_entry(self) -> None:
        """立绘 / SD:分块调色板载荷的头部、块表与几何必须自洽。"""
        import numpy as np

        checked = 0
        for pool in (POOL_SD, POOL_BODY, POOL_FACE):
            for entry in self.pools[pool]:
                if entry["kind"] == KIND_MISSING:
                    continue
                payload = self.payload(entry)
                width, height, palette_count, rows, blocks, _reserved, raw = \
                    BLOCK_HEADER.unpack_from(payload)
                self.assertEqual((width, height), (entry["w"], entry["h"]),
                                 f"{POOL_NAMES[pool]} {entry['index']} 几何不符")
                self.assertEqual(raw, rows * (width + 1))
                table = BLOCK_HEADER.size + palette_count * 3 + blocks * 4
                lengths = np.frombuffer(payload, dtype="<u4", count=blocks,
                                        offset=BLOCK_HEADER.size + palette_count * 3)
                self.assertEqual(table + int(lengths.sum()), len(payload))
                position = table
                decoded_rows = 0
                for index, length in enumerate(lengths):
                    block = zlib.decompress(payload[position:position + int(length)])
                    position += int(length)
                    self.assertLessEqual(len(block), raw, f"第 {index} 块超出行缓冲")
                    decoded_rows += len(block) // (width + 1)
                self.assertEqual(decoded_rows, height)
                checked += 1
        self.assertGreater(checked, 100)

    def test_sprite_table_indices_are_valid(self) -> None:
        rows = self.sprite_count
        self.assertGreater(rows, 1000)
        for index in range(rows):
            body, face, _fx, _fy = SPRITE.unpack_from(
                self.blob, self.sprite_off + 4 + index * SPRITE.size)
            if body != 0xFFFF:
                self.assertLess(body, self.asset_count)
                self.assertEqual(self.entries[body]["pool"], POOL_BODY)
                self.assertEqual(self.entries[body]["kind"], KIND_BODY)
            if face != 0xFFFF:
                self.assertLess(face, self.asset_count)
                self.assertEqual(self.entries[face]["pool"], POOL_FACE)
                self.assertEqual(self.entries[face]["kind"], KIND_FACE)

    def test_script_ids_fit_the_image_pools(self) -> None:
        """跨包一致性:剧本里出现的每个 id 都必须在图片包里存在。"""
        if not SCRIPT_PACK.is_file():
            self.skipTest("缺少剧本包")
        blob = SCRIPT_PACK.read_bytes()
        _version, sections = read_sections(blob, b"DRACUSC1")
        block_off, _count, _size = sections[2]
        block_total, page_blocks, page_count, per_block = SCN_BLOCK_HEADER.unpack_from(blob, block_off)
        blob_off, _c, _s = sections[3]
        records = []
        for index in range(page_blocks):
            off, comp, raw = SCN_BLOCK.unpack_from(blob, block_off + SCN_BLOCK_HEADER.size +
                                                   index * SCN_BLOCK.size)
            records.append(zlib.decompress(blob[blob_off + off:blob_off + off + comp]))
        pages = b"".join(records)
        self.assertEqual(len(pages), page_count * PAGE.size)
        max_bg = max_cg = max_sd = max_sprite = -1
        for number in range(page_count):
            text_off, text_len, cg, sprite, bg, sd, name, flags, cs, fs = \
                PAGE.unpack_from(pages, number * PAGE.size)
            max_bg = max(max_bg, -1 if bg == 0xFF else bg)
            max_sd = max(max_sd, -1 if sd == 0xFF else sd)
            max_cg = max(max_cg, -1 if cg == 0xFFFF else cg)
            max_sprite = max(max_sprite, -1 if sprite == 0xFFFF else sprite)
            self.assertLessEqual(name if name != 0xFF else 0, 0xFFFF)
        self.assertLess(max_bg, len(self.pools[POOL_BG]))
        self.assertLess(max_cg, len(self.pools[POOL_CG]))
        self.assertLess(max_sd, len(self.pools[POOL_SD]))
        self.assertLess(max_sprite, self.sprite_count)
        self.assertGreater(max_bg, 0)
        self.assertGreater(max_sprite, 0)


def main() -> int:
    suite = unittest.TestLoader().loadTestsFromTestCase(ImagePackTest)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    sys.exit(main())
