"""Canonical definition of the read-only galgame asset pack.

This module is the single source of truth for the on-flash layout consumed by
`main/gal/*`. Run it directly to regenerate the matching C header:

    python tools/gal/gal_format.py --emit-header main/gal/gal_format.h

Everything in the pack is little-endian and naturally aligned so the firmware
can memory-map the partition and read records in place without copying. Images
are stored in LVGL's indexed `LV_COLOR_FORMAT_I8` layout, which LVGL decodes one
scan line at a time, so no full-frame buffer is ever allocated.
"""

from __future__ import annotations

import struct

# --- Pack header -------------------------------------------------------------

MAGIC = 0x414C4147  # "GALA"
VERSION = 1

HEADER_STRUCT = "<IHHHHIIIIHH"  # gal_pack_header_t

# --- Image entries -----------------------------------------------------------

# Field order is chosen for natural alignment: every member lands on its own
# alignment boundary, so the C struct needs no padding.
IMAGE_ENTRY_STRUCT = "<HHhhBBHII"  # gal_image_entry_t

KIND_ALPHA = 0  # 256-entry ARGB palette + index bytes; transparency honoured
KIND_OPAQUE = 1  # 256-entry palette with A=255 + index bytes
KIND_SOLID = 2  # no payload; the RGB565 colour lives in `data_off`

PALETTE_ENTRIES = 256
PALETTE_BYTES = PALETTE_ENTRIES * 4

# --- Packed chapter ----------------------------------------------------------

CHAPTER_MAGIC = 0x434C4147  # "GALC"

CHAPTER_HEADER_STRUCT = "<IHHIIIIIIIHH"  # gal_chapter_header_t
CHAPTER_ENTRY_STRUCT = "<II"  # gal_chapter_entry_t
SCENE_REC_STRUCT = "<HHhhHHI"  # gal_scene_rec_t
DLG_REC_STRUCT = "<IHHHHHH"  # gal_dlg_rec_t

DLG_FLAG_END = 1 << 0
CHAPTER_FLAG_FINALE = 1 << 0

# `0xFFFF` in an image field means "no image".
IMG_NONE = 0xFFFF

ALIGN = 4

HEADER_SIZE = struct.calcsize(HEADER_STRUCT)
IMAGE_ENTRY_SIZE = struct.calcsize(IMAGE_ENTRY_STRUCT)
CHAPTER_ENTRY_SIZE = struct.calcsize(CHAPTER_ENTRY_STRUCT)
CHAPTER_HEADER_SIZE = struct.calcsize(CHAPTER_HEADER_STRUCT)
SCENE_REC_SIZE = struct.calcsize(SCENE_REC_STRUCT)
DLG_REC_SIZE = struct.calcsize(DLG_REC_STRUCT)

# --- C header ----------------------------------------------------------------

_C_HEADER_TEMPLATE = """\
/* Generated by tools/gal/gal_format.py -- do not edit by hand. */
#ifndef GAL_FORMAT_H
#define GAL_FORMAT_H

#include <stdint.h>

#define GAL_PACK_MAGIC 0x{magic:08X}u
#define GAL_PACK_VERSION {version}
#define GAL_PACK_HEADER_SIZE {header_size}
#define GAL_IMAGE_ENTRY_SIZE {image_entry_size}
#define GAL_CHAPTER_ENTRY_SIZE {chapter_entry_size}

#define GAL_IMG_KIND_ALPHA {kind_alpha}
#define GAL_IMG_KIND_OPAQUE {kind_opaque}
#define GAL_IMG_KIND_SOLID {kind_solid}

#define GAL_PALETTE_ENTRIES {palette_entries}
#define GAL_PALETTE_BYTES {palette_bytes}

#define GAL_CHAPTER_MAGIC 0x{chapter_magic:08X}u
#define GAL_CHAPTER_HEADER_SIZE {chapter_header_size}
#define GAL_SCENE_REC_SIZE {scene_rec_size}
#define GAL_DLG_REC_SIZE {dlg_rec_size}

#define GAL_DLG_FLAG_END {dlg_flag_end}
#define GAL_CHAPTER_FLAG_FINALE {chapter_flag_finale}

#define GAL_IMG_NONE 0xFFFFu

/* Pack header. */
typedef struct {{
    uint32_t magic;            /* GAL_PACK_MAGIC */
    uint16_t version;          /* GAL_PACK_VERSION */
    uint16_t header_size;      /* sizeof(gal_pack_header_t) */
    uint16_t image_count;
    uint16_t chapter_count;
    uint32_t image_index_off;  /* relative to the start of the pack */
    uint32_t name_blob_off;
    uint32_t name_blob_len;
    uint32_t script_index_off;
    uint16_t max_text_len;     /* longest UTF-8 dialogue line, excluding NUL */
    uint16_t reserved;
}} gal_pack_header_t;

/* One image. `data_off` and `name_off` are relative to the pack / name blob.
 * `offset_x`/`offset_y` place the image on screen when it is not anchored to
 * the origin; character patches are trimmed to their alpha bounding box, so
 * they carry the offset the trim removed. */
typedef struct {{
    uint16_t width;
    uint16_t height;
    int16_t offset_x;
    int16_t offset_y;
    uint8_t kind;              /* GAL_IMG_KIND_* */
    uint8_t reserved;
    uint16_t name_off;
    uint32_t data_off;
    uint32_t data_len;
}} gal_image_entry_t;

/* One chapter. `data_off` is relative to the start of the pack. */
typedef struct {{
    uint32_t data_off;
    uint32_t data_len;
}} gal_chapter_entry_t;

/* Packed chapter, read in place. */
typedef struct {{
    uint32_t magic;            /* GAL_CHAPTER_MAGIC */
    uint16_t scene_count;
    uint16_t dialogue_count;
    uint32_t scenes_off;
    uint32_t dialogues_off;
    uint32_t text_pool_off;
    uint32_t text_pool_len;
    uint32_t names_off;
    uint32_t names_len;
    uint32_t chapter_index;
    uint16_t flags;            /* GAL_CHAPTER_FLAG_* */
    uint16_t reserved;
}} gal_chapter_header_t;

/* One scene. `first_dialogue`/`dialogue_count` index the dialogue array.
 * `overlay_img` is drawn at (overlay_x, overlay_y) above the background and
 * below the character sprite. */
typedef struct {{
    uint16_t background_img;
    uint16_t overlay_img;
    int16_t overlay_x;
    int16_t overlay_y;
    uint16_t first_dialogue;
    uint16_t dialogue_count;
    uint32_t reserved;
}} gal_scene_rec_t;

/* One dialogue line. Text and speaker name are NUL-terminated UTF-8 slices of
 * the chapter text pool. */
typedef struct {{
    uint32_t text_off;
    uint16_t text_len;
    uint16_t name_off;
    uint16_t name_len;
    uint16_t body_img;
    uint16_t face_img;
    uint16_t flags;
}} gal_dlg_rec_t;

/* Layout guards: these fail the build if the C compiler disagrees with the
 * packer, instead of silently reading the wrong bytes at runtime. */
_Static_assert(sizeof(gal_pack_header_t) == GAL_PACK_HEADER_SIZE, "pack header size mismatch");
_Static_assert(sizeof(gal_image_entry_t) == GAL_IMAGE_ENTRY_SIZE, "image entry size mismatch");
_Static_assert(sizeof(gal_chapter_entry_t) == GAL_CHAPTER_ENTRY_SIZE, "chapter entry size mismatch");
_Static_assert(sizeof(gal_chapter_header_t) == GAL_CHAPTER_HEADER_SIZE, "chapter header size mismatch");
_Static_assert(sizeof(gal_scene_rec_t) == GAL_SCENE_REC_SIZE, "scene record size mismatch");
_Static_assert(sizeof(gal_dlg_rec_t) == GAL_DLG_REC_SIZE, "dialogue record size mismatch");

#endif /* GAL_FORMAT_H */
"""


def emit_c_header() -> str:
    return _C_HEADER_TEMPLATE.format(
        magic=MAGIC,
        version=VERSION,
        header_size=HEADER_SIZE,
        image_entry_size=IMAGE_ENTRY_SIZE,
        chapter_entry_size=CHAPTER_ENTRY_SIZE,
        kind_alpha=KIND_ALPHA,
        kind_opaque=KIND_OPAQUE,
        kind_solid=KIND_SOLID,
        palette_entries=PALETTE_ENTRIES,
        palette_bytes=PALETTE_BYTES,
        chapter_magic=CHAPTER_MAGIC,
        chapter_header_size=CHAPTER_HEADER_SIZE,
        scene_rec_size=SCENE_REC_SIZE,
        dlg_rec_size=DLG_REC_SIZE,
        dlg_flag_end=DLG_FLAG_END,
        chapter_flag_finale=CHAPTER_FLAG_FINALE,
    )


def main() -> int:
    import argparse
    import pathlib

    parser = argparse.ArgumentParser(description="galgame asset pack format")
    parser.add_argument("--emit-header", metavar="PATH", help="write the matching C header")
    parser.add_argument("--print-sizes", action="store_true", help="show the computed layout")
    args = parser.parse_args()

    if args.emit_header:
        path = pathlib.Path(args.emit_header)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(emit_c_header(), encoding="utf-8", newline="\n")
        print(f"wrote {path}")

    if args.print_sizes or not (args.emit_header or args.print_sizes):
        print(f"pack header {HEADER_SIZE}  image entry {IMAGE_ENTRY_SIZE}  chapter entry {CHAPTER_ENTRY_SIZE}")
        print(f"chapter header {CHAPTER_HEADER_SIZE}  scene rec {SCENE_REC_SIZE}  dialogue rec {DLG_REC_SIZE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
