/* Generated by tools/gal/gal_format.py -- do not edit by hand. */
#ifndef GAL_FORMAT_H
#define GAL_FORMAT_H

#include <stdint.h>

#define GAL_PACK_MAGIC 0x414C4147u
#define GAL_PACK_VERSION 1
#define GAL_PACK_HEADER_SIZE 32
#define GAL_IMAGE_ENTRY_SIZE 20
#define GAL_CHAPTER_ENTRY_SIZE 8

#define GAL_IMG_KIND_ALPHA 0
#define GAL_IMG_KIND_OPAQUE 1
#define GAL_IMG_KIND_SOLID 2

#define GAL_PALETTE_ENTRIES 256
#define GAL_PALETTE_BYTES 1024

#define GAL_CHAPTER_MAGIC 0x434C4147u
#define GAL_CHAPTER_HEADER_SIZE 40
#define GAL_SCENE_REC_SIZE 16
#define GAL_DLG_REC_SIZE 16

#define GAL_DLG_FLAG_END 1
#define GAL_CHAPTER_FLAG_FINALE 1

#define GAL_IMG_NONE 0xFFFFu

/* Pack header. */
typedef struct {
    uint32_t magic;            /* GAL_PACK_MAGIC */
    uint16_t version;          /* GAL_PACK_VERSION */
    uint16_t header_size;      /* sizeof(gal_pack_header_t) */
    uint16_t image_count;
    uint16_t chapter_count;
    uint32_t image_index_off;  /* relative to the start of the pack */
    uint32_t name_blob_off;
    uint32_t name_blob_len;
    uint32_t script_index_off;
    uint16_t max_text_len;     /* longest UTF-8 dialogue line, excluding NUL */
    uint16_t reserved;
} gal_pack_header_t;

/* One image. `data_off` and `name_off` are relative to the pack / name blob.
 * `offset_x`/`offset_y` place the image on screen when it is not anchored to
 * the origin; character patches are trimmed to their alpha bounding box, so
 * they carry the offset the trim removed. */
typedef struct {
    uint16_t width;
    uint16_t height;
    int16_t offset_x;
    int16_t offset_y;
    uint8_t kind;              /* GAL_IMG_KIND_* */
    uint8_t reserved;
    uint16_t name_off;
    uint32_t data_off;
    uint32_t data_len;
} gal_image_entry_t;

/* One chapter. `data_off` is relative to the start of the pack. */
typedef struct {
    uint32_t data_off;
    uint32_t data_len;
} gal_chapter_entry_t;

/* Packed chapter, read in place. */
typedef struct {
    uint32_t magic;            /* GAL_CHAPTER_MAGIC */
    uint16_t scene_count;
    uint16_t dialogue_count;
    uint32_t scenes_off;
    uint32_t dialogues_off;
    uint32_t text_pool_off;
    uint32_t text_pool_len;
    uint32_t names_off;
    uint32_t names_len;
    uint32_t chapter_index;
    uint16_t flags;            /* GAL_CHAPTER_FLAG_* */
    uint16_t reserved;
} gal_chapter_header_t;

/* One scene. `first_dialogue`/`dialogue_count` index the dialogue array.
 * `overlay_img` is drawn at (overlay_x, overlay_y) above the background and
 * below the character sprite. */
typedef struct {
    uint16_t background_img;
    uint16_t overlay_img;
    int16_t overlay_x;
    int16_t overlay_y;
    uint16_t first_dialogue;
    uint16_t dialogue_count;
    uint32_t reserved;
} gal_scene_rec_t;

/* One dialogue line. Text and speaker name are NUL-terminated UTF-8 slices of
 * the chapter text pool. */
typedef struct {
    uint32_t text_off;
    uint16_t text_len;
    uint16_t name_off;
    uint16_t name_len;
    uint16_t body_img;
    uint16_t face_img;
    uint16_t flags;
} gal_dlg_rec_t;

/* Layout guards: these fail the build if the C compiler disagrees with the
 * packer, instead of silently reading the wrong bytes at runtime. */
_Static_assert(sizeof(gal_pack_header_t) == GAL_PACK_HEADER_SIZE, "pack header size mismatch");
_Static_assert(sizeof(gal_image_entry_t) == GAL_IMAGE_ENTRY_SIZE, "image entry size mismatch");
_Static_assert(sizeof(gal_chapter_entry_t) == GAL_CHAPTER_ENTRY_SIZE, "chapter entry size mismatch");
_Static_assert(sizeof(gal_chapter_header_t) == GAL_CHAPTER_HEADER_SIZE, "chapter header size mismatch");
_Static_assert(sizeof(gal_scene_rec_t) == GAL_SCENE_REC_SIZE, "scene record size mismatch");
_Static_assert(sizeof(gal_dlg_rec_t) == GAL_DLG_REC_SIZE, "dialogue record size mismatch");

#endif /* GAL_FORMAT_H */
